global:
    scrape_interval: 5s
    external_labels:
        monitor: 'my-monitor'

scrape_configs:

  - job_name: 'prometheus'

    scrape_interval: 10s
    scrape_timeout: 5s

    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'myFirstJob'
    static_configs:
      - targets: ['<<MY IP HERE>>:5000']
